# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Maya Ravichandran
tagline:          'Personal Website'
description:      'Computer Science Student'
url:              https://maravichandran.github.io
baseurl:          /

author:
  name:           'Maya Ravichandran'
  url:            https://www.linkedin.com/in/maya-ravichandran/

paginate:         5

# libraries
gems:             [jekyll-paginate, jekyll-gist]